# Generated by Django 5.1.6 on 2025-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='status',
            field=models.IntegerField(choices=[(1, 'خریداری شده'), (2, 'محمد'), (3, 'مهدی'), (4, 'امیرحسین'), (5, 'امیرمحمد')], default=1),
        ),
    ]
