# Generated by Django 5.1.6 on 2025-02-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0002_purchaseitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
