# Generated by Django 3.2.25 on 2025-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0003_alter_purchaseitem_purchase_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
