# Generated by Django 3.2.25 on 2025-02-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0004_alter_budget_total_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
