# Generated by Django 3.2.25 on 2025-02-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0005_alter_purchaseitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
