# Generated by Django 3.2.25 on 2025-02-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_manager', '0006_auto_20250227_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='total_budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='price',
            field=models.IntegerField(),
        ),
    ]
